sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wcw231407
  qi-niu:
    endpoint: http://img.wcw231407.cn/
    access-key-id: RfAPWyXFwNHF6Z8OBQipIg_1iNIp-KJj5A-Fe5eL
    access-key-secret: -OUMlQVUczKKAVBVp9Q5xBUIasMw1hBRdXqCFJ9B
    bucket-name: fancydog
  wechat:
    appid: wx35e39bf1a84534a8
    secret: ebd4a220d68869aa62beb88066b046c8
